
export const mockInventoryData = [
  {
    id: "1",
    shoe_name: "Air Max 90",
    size: 9,
    category: "men",
    stock: 15,
    buying_price: 3500,
    selling_price: 6500,
    profit: 3000,
  },
  {
    id: "2",
    shoe_name: "Ultraboost 22",
    size: 10,
    category: "men",
    stock: 8,
    buying_price: 4200,
    selling_price: 7800,
    profit: 3600,
  },
  {
    id: "3",
    shoe_name: "Chuck Taylor",
    size: 8,
    category: "men",
    stock: 20,
    buying_price: 1800,
    selling_price: 3500,
    profit: 1700,
  },
  {
    id: "4",
    shoe_name: "ZoomX Vaporfly",
    size: 9.5,
    category: "men",
    stock: 5,
    buying_price: 6000,
    selling_price: 12000,
    profit: 6000,
  },
  {
    id: "5",
    shoe_name: "Air Jordan 1",
    size: 8.5,
    category: "women",
    stock: 12,
    buying_price: 4500,
    selling_price: 8500,
    profit: 4000,
  },
  {
    id: "6",
    shoe_name: "Rihanna Fenty",
    size: 7,
    category: "women",
    stock: 9,
    buying_price: 3800,
    selling_price: 7200,
    profit: 3400,
  },
  {
    id: "7",
    shoe_name: "Stan Smith",
    size: 6.5,
    category: "women",
    stock: 14,
    buying_price: 2200,
    selling_price: 4500,
    profit: 2300,
  },
  {
    id: "8",
    shoe_name: "Kids Runner",
    size: 4,
    category: "kids",
    stock: 18,
    buying_price: 1200,
    selling_price: 2800,
    profit: 1600,
  },
  {
    id: "9",
    shoe_name: "Junior Sport",
    size: 5,
    category: "kids",
    stock: 15,
    buying_price: 1500,
    selling_price: 3200,
    profit: 1700,
  },
  {
    id: "10",
    shoe_name: "Comfort Slippers",
    size: 8,
    category: "slippers",
    stock: 25,
    buying_price: 500,
    selling_price: 1200,
    profit: 700,
  },
  {
    id: "11",
    shoe_name: "Luxury Slides",
    size: 9,
    category: "slippers",
    stock: 10,
    buying_price: 800,
    selling_price: 2000,
    profit: 1200,
  },
];
